name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: phillipj/stale@9300b44d46229c07edd483df1527f3c21c1403c0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-close: 1
        stale-pr-label: stalled
        stale-issue-label: stalled
        remove-stale-when-updated: false
        # deactivates automatic stale labelling as we prefer to do that manually
        days-before-stale: -1
